spring:
  application:
    name: springbatch
  batch:
    jdbc:
      initialize-schema: embedded
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/springbatch
    username: springbatch
    password: springbatch!
